name: Publish Docs

on:
  push:
    branches: [main] # only if commit message starts with "docs "
  workflow_dispatch:

jobs:
  publish-docs:
    name: Build sphinx documentation on docs branch
    runs-on: ubuntu-latest
    if: |
      ${{ github.event_name=='workflow_dispatch' 
      || (github.event_name=='push' 
      && (startsWith(github.ref, 'refs/tags') 
      || startsWith(github.event.head_commit.message, 'docs ')))}}
    steps:
      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2

      - name: Setup Python dependencies
        run: |
          python -m pip install -U pip
          pip install -r docsrc/requirements.txt
          pip install -e .

      - name: Build and Commit
        run: |
          make html
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f docs
          git commit -m "github action"
        # uses: sphinx-notes/pages@master
        # with:
        #   documentation_path: docsrc
      - name: Push changes to docs branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          force: true
